/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as QuoteRouteImport } from './routes/quote'
import { Route as ApiQuoteInitiateRouteImport } from './routes/api/quote/initiate'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuoteRoute = QuoteRouteImport.update({
  id: '/quote',
  path: '/quote',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiQuoteInitiateRoute = ApiQuoteInitiateRouteImport.update({
  id: '/api/quote/initiate',
  path: '/api/quote/initiate',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/quote': typeof QuoteRoute
  '/api/quote/initiate': typeof ApiQuoteInitiateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/quote': typeof QuoteRoute
  '/api/quote/initiate': typeof ApiQuoteInitiateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/quote': typeof QuoteRoute
  '/api/quote/initiate': typeof ApiQuoteInitiateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/quote' | '/api/quote/initiate'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/quote' | '/api/quote/initiate'
  id: '__root__' | '/' | '/quote' | '/api/quote/initiate'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  QuoteRoute: typeof QuoteRoute
  ApiQuoteInitiateRoute: typeof ApiQuoteInitiateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quote': {
      id: '/quote'
      path: '/quote'
      fullPath: '/quote'
      preLoaderRoute: typeof QuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/quote/initiate': {
      id: '/api/quote/initiate'
      path: '/api/quote/initiate'
      fullPath: '/api/quote/initiate'
      preLoaderRoute: typeof ApiQuoteInitiateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  QuoteRoute: QuoteRoute,
  ApiQuoteInitiateRoute: ApiQuoteInitiateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
